# Generated by Django 3.2.25 on 2025-01-28 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0002_auto_20250128_0956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='women',
            name='slug',
            field=models.SlugField(max_length=100, unique=True),
        ),
    ]
