# Generated by Django 3.2.25 on 2025-02-05 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0008_auto_20250203_1210'),
    ]

    operations = [
        migrations.AddField(
            model_name='husband',
            name='n_count',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
