# Generated by Django 5.1.7 on 2025-03-18 08:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("women", "0010_auto_20250213_0829"),
    ]

    operations = [
        migrations.CreateModel(
            name="UploadFiles",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="uploads_model")),
            ],
        ),
    ]
