"""
Django settings for sitewomen project.

Generated by 'django-admin startproject' using Django 3.2.25.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-xbe)$96&m%lq4i)3p_7ba8*9zwuf@=i+5pq&lq9)9pt1vblm^b'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True
#DEBUG = False #что бы работала статика надо запускать сервер - python manage.py runserver --insecure

ALLOWED_HOSTS = ['127.0.0.1', 'localhost', 'sitewomen.ru']
#ALLOWED_HOSTS = ['127.0.0.1']

INTERNAL_IPS = [
    # ...
    "127.0.0.1",
    # ...
]

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    "debug_toolbar",

    'django_extensions',

    'women.apps.WomenConfig',
    'users.apps.UsersConfig',

    'social_django',
    'captcha',

    'django.contrib.sites',#управляет глобальными настройками карты сайта
    'django.contrib.sitemaps', #формирует карту сайта
]

MIDDLEWARE = [
    "debug_toolbar.middleware.DebugToolbarMiddleware",
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
#    "django.middleware.cache.UpdateCacheMiddleware", #для кеширования всего сайта целиком
    'django.middleware.common.CommonMiddleware',
#    "django.middleware.cache.FetchFromCacheMiddleware", #для кеширования всего сайта целиком
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    #"debug_toolbar.middleware.DebugToolbarMiddleware",
]
# CACHE_MIDDLEWARE_ALIAS ='default' #для кеширования всего сайта целиком
# CACHE_MIDDLEWARE_SECONDS=10       #для кеширования всего сайта целиком
# CACHE_MIDDLEWARE_KEY_PREFIX='sitewomen' #для кеширования всего сайта целиком

ROOT_URLCONF = 'sitewomen.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            BASE_DIR / 'templates'
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'users.context_processors.get_women_context',
            ],
        },
    },
]

WSGI_APPLICATION = 'sitewomen.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        'NAME': 'sitewomen_db',
        'USER': 'sitewomen',
        'PASSWORD': '11111qqqqq',
        'HOST': 'localhost',
        'PORT': '5432',
    }
}

CACHES = {
    "default": {
        #"BACKEND": "django.core.cache.backends.dummy.DummyCache",
        "BACKEND": "django.core.cache.backends.redis.RedisCache",
        "LOCATION": "redis://127.0.0.1:6379",
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

#LANGUAGE_CODE = 'en-us'
LANGUAGE_CODE = 'ru-RU'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [ BASE_DIR / 'sitewomen/static' ]# нестандартный путь - если статика находится не в приложении

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

MEDIA_ROOT = BASE_DIR / "media"
MEDIA_URL='/media/'

LOGIN_REDIRECT_URL="women:index"
LOGOUT_REDIRECT_URL="women:index"
LOGIN_URL="users:login_user" #если пользователь не авторизован

AUTHENTICATION_BACKENDS=[
    'social_core.backends.github.GithubOAuth2',
    "django.contrib.auth.backends.ModelBackend",
    "users.authentication.EmailAuthBackend",
  ]

#EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"

EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST="smtp.yandex.ru"
EMAIL_PORT=465
EMAIL_HOST_USER="asdfg2105fomencko@yandex.ru"
EMAIL_HOST_PASSWORD="qctznmqgnttcgbgs"
EMAIL_USE_SSL=True

DEFAULT_FROM_EMAIL=EMAIL_HOST_USER
SERVER_EMAIL=EMAIL_HOST_USER
EMAIL_ADMIN=EMAIL_HOST_USER

AUTH_USER_MODEL = "users.User" #при переопределении таблицы authuser удалить все миграции и базу и создать заново

DEFAULT_USER_IMAGE = MEDIA_URL + "users/default.jpg"

#SOCIAL_AUTH_JSONFIELD_ENABLED = True # для PostgreSQL

SOCIAL_AUTH_GITHUB_KEY = 'Ov23li6PpYCNJhSZbwCY'
SOCIAL_AUTH_GITHUB_SECRET ='838808f9ef67a1fed7194c49b9ef3ce127761494'

SOCIAL_AUTH_PIPELINE = (
    'social_core.pipeline.social_auth.social_details',
    'social_core.pipeline.social_auth.social_uid',
    'social_core.pipeline.social_auth.auth_allowed',
    'social_core.pipeline.social_auth.social_user',
    'social_core.pipeline.user.get_username',
    'social_core.pipeline.social_auth.associate_by_email',  # <--- enable this one
    'social_core.pipeline.user.create_user',
    'users.pipeline.new_users_handler',
    'social_core.pipeline.social_auth.associate_user',
    'social_core.pipeline.social_auth.load_extra_data',
    'social_core.pipeline.user.user_details',
)

CAPTCHA_FONT_SIZE=44
CAPTCHA_IMAGE_SIZE=(200,80)
CAPTCHA_BACKGROUND_COLOR="yellow"

SITE_ID=1 # для карты сайта